<?php
    $identity = $this->getUserByIdentity();
    if (is_null($identity)) :
?>
<div id="auth" class="modal hide" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    
    <img class="Icerar pull-right point" src="/zeta/0.png" width="9" height="9" data-dismiss="modal" aria-hidden="true" />    
    
    <ul class="nav nav-tabs" id="SignTab">
        <li><h2>Entrada</h2></li>
        <li><a href="#signup" role="button" data-toggle="modal" data-dismiss="modal"><h2>Regístrate</h2></a></li>
    </ul>
            
    <form class="form-horizontal" name="signin_form_top" enctype="application/x-www-form-urlencoded" method="post" action="<?=$this->url(array(), 'signin');?>">
            <div class="AU1">
                <div class="w100 clear mb10">
                <label class="AUlabel f12" for="AUemail" >E-mail</label><input class="" type="text" id="AUemail" placeholder="E-mail" name="email" maxlength="50" />
                </div>
                <div class="w100 clear mb10">
                <label class="AUlabel f12" for="AUcontra" >Contraseña</label><input class="" type="password" id="AUcontra" placeholder="Contraseña" name="password" maxlength="30" />
                </div>
            </div>
            <div class="AU2">
                <input type="hidden" name="referrer" value="<?php print Zend_Controller_Front::getInstance()->getRequest()->getServer('HTTP_REFERER'); ?>" id="referrer">
                <input type="submit" class="btn" value="Entrar" />
            </div>

            <div class="w100 clear mb20">
                ¿<a href="<?= $this->url(array(), 'userrestore') ?>">Olvidó su contraseña</a>? &nbsp;&nbsp; ¿No tiene cuenta? <a href="#signup" role="button" data-toggle="modal" data-dismiss="modal">Regístrate</a>!
            </div>

            <div class="AU3 bor4">
                <div class="AU2">
                    <a id="facebook" href="<?= $this->url(array('social' => 'facebook'), 'auth') ?>"><img class="Iconectar" src="/zeta/0.png" width="105" height="21" src="" /></a>
                </div>
                <div class="AU5 pull-right f10 grey">
                    Si usted tiene una cuenta en Facebook, se puede<br />ir una comprobación rápida.
                </div>
            </div>
    </form>

</div>    

        
<div id="signup" class="modal hide" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <?php
        $auth = Zend_Auth::getInstance();
        if (!$auth->hasIdentity()) :
    ?>
<script type="text/javascript" src="/js/users/signup.js"></script>
    <?php
        endIf;
    ?>  
    
    <img class="Icerar pull-right point" src="/zeta/0.png" width="9" height="9" data-dismiss="modal" aria-hidden="true" />    
    
    <ul class="nav nav-tabs" id="SignTab">
        <li><a href="#auth" role="button" data-toggle="modal" data-dismiss="modal"><h2>Entrada</h2></a></li>
        <li><h2>Regístrate</h2></li>
    </ul>

    <style>
        .REG1 {width: 100%;}
        .REGlabel {display: inline-block; width: 130px;}
        select#REGday_birth {width: 50px;}
        select#REGmonth_birth {width: 125px;}
        select#REGyear_birth {width: 125px;}
        select#REGsex {width: 178px;}
        select#REGcity_id {width: 178px;}

    </style>
    <form id="signupForm" class="form-horizontal" enctype="application/x-www-form-urlencoded" method="post" action="<?=$this->url(array(), 'signup');?>">
            <div class="REG1">
                <div class="w100 clear mb10">
                <label class="REGlabel f12" for="REGnombre" >Nombre de usuario</label><input type="text" id="REGnombre" placeholder="Use solo símbolos latinos y no más de un espacio" name="username" maxlength="20" />
                </div>
                <div class="w100 clear mb10">
                <label class="REGlabel f12" for="REGemail" >E-mail</label><input type="text" id="REGemail" placeholder="E-mail" name="email" maxlength="30" />
                </div>
                <div class="w100 clear mb10">
                <label class="REGlabel f12" for="REGcontrasena" >Contraseña</label><input type="password" id="REGcontrasena" placeholder="Símbolos latinos y numeros" name="password" maxlength="30" />
                </div>
                <div class="w100 clear mb10">
                <label class="REGlabel f12" for="REGconfirmPassword" >Confirmar contraseña</label><input type="password" id="REGconfirmPassword" placeholder="Símbolos latinos y numeros" name="confirmPassword" maxlength="30" />
                </div>
                <div class="w100 clear mb10">
                <label class="REGlabel f12" for="REGnombres" >Nombres</label><input type="text" id="REGnombres" placeholder="Use solo símbolos latinos y no más de un espacio" name="firstname" maxlength="40" />
                </div>
                <div class="w100 clear mb10">
                <label class="REGlabel f12" for="REGlastname" >Apellidos</label><input type="text" id="REGlastname" placeholder="Use solo símbolos latinos y no más de un espacio" name="lastname" maxlength="40" />
                </div>
                <div class="w100 f10 grey clear mb10">
                Le aconsejamos indicar información correcta — eso agilizara la comunicación y ayudará a sus amigos a encontrarle.
                </div>
                <div class="w100 clear mb10">
                <label class="REGlabel f12" for="REGday_birth" >Fecha de nacimiento</label>
                <select name="day_birth" id="REGday_birth" />
                    <option selected value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                    <option value="9">9</option>
                    <option value="10">10</option>
                    <option value="11">11</option>
                    <option value="12">12</option>
                    <option value="13">13</option>
                    <option value="14">14</option>
                    <option value="15">15</option>
                    <option value="16">16</option>
                    <option value="17">17</option>
                    <option value="18">18</option>
                    <option value="19">19</option>
                    <option value="20">20</option>
                    <option value="21">21</option>
                    <option value="22">22</option>
                    <option value="23">23</option>
                    <option value="24">24</option>
                    <option value="25">25</option>
                    <option value="26">26</option>
                    <option value="27">27</option>
                    <option value="28">28</option>
                    <option value="29">29</option>
                    <option value="30">30</option>
                    <option value="31">31</option>
                </select>
                <select name="month_birth" id="REGmonth_birth">
                    <option selected value="1">Enero</option>
                    <option value="2">Febrero</option>
                    <option value="3">Marzo</option>
                    <option value="4">Abril</option>
                    <option value="5">Mayo</option>
                    <option value="6">Junio</option>
                    <option value="7">Julio</option>
                    <option value="8">Agosto</option>
                    <option value="9">Septiembre</option>
                    <option value="10">Octubre</option>
                    <option value="11">Noviembre</option>
                    <option value="12">Deciembre</option>
                </select>
                <select name="year_birth" id="REGyear_birth">
                    <option value="0">Secreto</option>
                    <option value="1940">1940</option>
                    <option value="1941">1941</option>
                    <option value="1942">1942</option>
                    <option value="1943">1943</option>
                    <option value="1944">1944</option>
                    <option value="1945">1945</option>
                    <option value="1946">1946</option>
                    <option value="1947">1947</option>
                    <option value="1948">1948</option>
                    <option value="1949">1949</option>
                    <option value="1950">1950</option>
                    <option value="1951">1951</option>
                    <option value="1952">1952</option>
                    <option value="1953">1953</option>
                    <option value="1954">1954</option>
                    <option value="1955">1955</option>
                    <option value="1956">1956</option>
                    <option value="1957">1957</option>
                    <option value="1958">1958</option>
                    <option value="1959">1959</option>
                    <option value="1960">1960</option>
                    <option value="1961">1961</option>
                    <option value="1962">1962</option>
                    <option value="1963">1963</option>
                    <option value="1964">1964</option>
                    <option value="1965">1965</option>
                    <option value="1966">1966</option>
                    <option value="1967">1967</option>
                    <option value="1968">1968</option>
                    <option value="1969">1969</option>
                    <option value="1970">1970</option>
                    <option value="1971">1971</option>
                    <option value="1972">1972</option>
                    <option value="1973">1973</option>
                    <option value="1974">1974</option>
                    <option value="1975">1975</option>
                    <option value="1976">1976</option>
                    <option value="1977">1977</option>
                    <option value="1978">1978</option>
                    <option value="1979">1979</option>
                    <option value="1980">1980</option>
                    <option value="1981">1981</option>
                    <option value="1982">1982</option>
                    <option value="1983">1983</option>
                    <option value="1984">1984</option>
                    <option value="1985">1985</option>
                    <option value="1986">1986</option>
                    <option selected value="1987">1987</option>
                    <option value="1988">1988</option>
                    <option value="1989">1989</option>
                    <option value="1990">1990</option>
                    <option value="1991">1991</option>
                    <option value="1992">1992</option>
                    <option value="1993">1993</option>
                    <option value="1994">1994</option>
                    <option value="1995">1995</option>
                    <option value="1996">1996</option>
                    <option value="1997">1997</option>
                    <option value="1998">1998</option>
                    <option value="1999">1999</option>
                    <option value="2000">2000</option>
                    <option value="2001">2001</option>
                    <option value="2002">2002</option>
                    <option value="2003">2003</option>
                    <option value="2004">2004</option>
                    <option value="2005">2005</option>
                    <option value="2006">2006</option>
                </select>
                </div>
                <div class="w100 clear mb10">
                <label class="REGlabel f12" for="REGsex" >Género</label>
                <select name="sex" id="REGsex">
                    <option selected value="1">Masculino</option>
                    <option value="2">Femenino</option>
                </select>
                </div>
                <div class="w100 clear mb10">
                <label class="REGlabel f12" for="REGcity_id" >Ciudad</label>
                <select id="REGcity_id" name="city_id">
                <?php
                    // придумать потом как это сделать по-другому
                    $table = new Application_Model_Table_Cities();
                    $cities = $table->getAll();
                    foreach ($cities as $key=>$item) :
                ?>                    
                    <option <?php if ($key==1) print 'selected="selected" ' ?>value="<?= $item->id ?>"><?= $item->name ?></option>
                <?php
                    endForeach;
                ?>                    
                    <option value="0">Otra ciudad...</option>
                </select>
                </div>
                <div class="w100 clear mb20" id="other_city">
                <label class="REGlabel f12" for="REGother_city" >Su ciudad</label><input type="text" id="REGother_city" placeholder="Escriba el nombre..." name="city_other" maxlength="40" />
                </div>

                <div class="w100 clear mb20">
                <input id="REGsubmit" type="button" onclick="javascript:sendform()" class="btn" value="Registrarse" />
                </div>
            </div>

            <div class="AU3 bor4">
                <div class="AU2">
                    <a id="facebook" href="<?= $this->url(array('social' => 'facebook'), 'auth') ?>"><img class="Iconectar" src="/zeta/0.png" width="105" height="21" src="" /></a>
                </div>
                <div class="AU5 pull-right f10 grey">
                    Si usted tiene una cuenta en Facebook, se puede<br />ir una comprobación rápida.
                </div>
            </div>
    </form>
    
</div>
<?php
    endIf;
?>