<?php
    $user = $this->GetUserByIdentity();
?>
<?php
    if (!empty($this->messages)):
        if ($this->newMessageCount > 0) :
?>
            <p class="break mar-bot">
                <strong><?= $this->newMessageCount ?> <?= Users_MessagesController::pluralForm($this->newMessageCount, $this->messWord); ?></strong>
            </p>
<?php 
        endif;
?>

    <?php
        foreach ($this->messages as $message) :            
            $who = $message->getFrom();
            if ($user->id == $who->id)
                $who = $message->getTo();
    ?>
					
        <div class="Qblock Qblock5 mb20">

		<div class="Qmens1">
		<?= $who->getAvatar(90,90) ?>
		</div>
	
                <div class="Qmens2 f13">
                        <strong><?= $who->getUserName() ?></strong>
                         <?php if (strlen($message->getMessage()) > 310) : ?>
                            <span id="messageShortText_<?= $message->id ?>"><?= mb_substr($message->getMessage(), 0, 308, "UTF-8") . " " ?> <a href="javascript:void(0)" class="lnone" onclick="getFullText(<?= $message->id; ?>)"><strong>mostrar todo...</strong></a></span>
                        <?php endif; ?>
                            <span id="messageText_<?= $message->id ?>" <?php if (strlen($message->getMessage()) > 310) : ?> style="display:none;" <?php endif; ?>><?= $message->getMessage() ?></span>
                        <div class="clear w100 f11 grey"><?= $this->dateFormatMessages($message->date) ?></div>
                </div>
		<div class="Qmens3 pull-right">
		    <?php
			if ($user && $user->id != $message->id_user_from) :
		    ?>
                    <a class="mb10" href="<?=$this->url(array('messageId' => $message->id), 'replyto')?>" title="Responder"><img class="Iresponder" src="/zeta/0.png" width="19" height="15" alt="" /></a>
		    <?php
			endIf;
		    ?>
		    <a class="mb10" id="message-delete" title="Eliminar" href="<?php if ($user && $user->id != $message->id_user_from): ?> <?=$this->url(array('messageId' => $message->id, 'action' => 'deleteinbox'), 'usermessage')?>
		    <?php else : ?> <?=$this->url(array('messageId' => $message->id, 'action' => 'deleteoutbox'), 'usermessage')?> <?php endIf; ?>">
		    <img class="Ieliminar1" src="/zeta/0.png" width="19" height="15" alt="" /></a>
		</div>
        </div>
<?php
        endforeach; 
    endif;
?>
