<div class="standard_element_container">    
    <?php
        // label
        if (!is_null($this->element->getLabel())) { //         $this->formLabel($this->element->getName(),$this->element->getLabel())
    ?>
    <label class="standard_label"><?=$this->element->getLabel()?><?php if($this->element->isRequired()) print "*"; ?></label>
    <?php
        }
    ?>
    <textarea id="<?=$this->element->getName()?>" name="<?=$this->element->getName()?>" <?php if (!is_null($this->maxlength)) { print "maxlength=\"".$this->maxlength."\""; } ?> class="imperavi_textarea"><?=$this->element->getValue()?></textarea>
</div>
<?php if (!is_null($this->element->getDescription())) : ?><div class="standard_element_help"><?php echo $this->element->getDescription() ?></div><?php endIf; ?>
<?php
    if (count($this->element->getMessages()) > 0) {
        //print $this->formErrors($this->element->getMessages())
        foreach ($this->element->getMessages() as $key=>$name) {
?>
<div class="check_error"><span class="COLLECTION"></span><?=$name;?></div>
<?php
        }
    }
?>