<div class="standard_element_container">
    
    <?php
        // label
        if (!is_null($this->element->getLabel())) { //         $this->formLabel($this->element->getName(),$this->element->getLabel())
    ?>
    <label class="standard_label"><?=$this->element->getLabel()?><?php if($this->element->isRequired()) print "*"; ?></label>
    <?php
        }
    ?>
    <input id="<?=$this->element->getName()?>" name="<?=$this->element->getName()?>" type="text" <?php if (!is_null($this->maxlength)) { print "maxlength=\"".$this->maxlength."\""; } ?> value="<?=$this->element->getValue()?>" class="date-pick" />

</div>

<div class="standard_element_help"><?php echo $this->element->getDescription() ?></div>

<?php    
    if (count($this->element->getMessages()) > 0) {
        //print $this->formErrors($this->element->getMessages())
        foreach ($this->element->getMessages() as $key=>$name) {
?>
<div class="check_error"><span class="COLLECTION"></span><?=$name;?></div>
<?php
        }
    }
?>