<?php
    // label
    if (!is_null($this->element->getLabel())) { //         $this->formLabel($this->element->getName(),$this->element->getLabel())
?>
<label class="standard_label"><?=$this->element->getLabel()?><?php if($this->element->isRequired()) print "*"; ?></label>
<?php
    }
?>
<select name="<?=$this->element->getName()?>[]" id="<?=$this->element->getName()?>" size="<?=$this->element->size?>" class="standard_select" multiple="multiple">
<?php
    foreach ($this->element->getmultiOptions() as $key=>$name) {
        if (is_array($name)) {
            print "<optgroup label='" . $key . "'>";
            foreach ($name as $subkey=>$subname) {
?>
    <option <?php if($this->element->getValue()==$subkey) echo "selected";  ?> value="<?=$subkey?>"><?=$subname?></option>
<?php                
            }
            print "</optgroup>";
        } else {
?>
    <option <?php if($this->element->getValue()==$key) echo "selected";  ?> value="<?=$key?>"><?=$name?></option>
<?php
        }
    }
?>
</select>