<?php
    // label
    if (!is_null($this->element->getLabel())) { //         $this->formLabel($this->element->getName(),$this->element->getLabel())
?>
<label class="standard_label"><?=$this->element->getLabel()?><?php if($this->element->isRequired()) print "*"; ?></label>
<?php
    }
?>
<select name="<?=$this->element->getName()?>" id="<?=$this->element->getName()?>" class="standard_select">
<?php
    foreach ($this->element->getmultiOptions() as $key=>$name) {
?>
    <option <?php if($this->element->getValue()==$key) echo "selected";  ?> value="<?=$key?>"><?=$name?></option>
<?php
    }
?>
</select>