<?php
    // label
    if (!is_null($this->element->getLabel())) { //         $this->formLabel($this->element->getName(),$this->element->getLabel())
        if (!isset($this->labelclass)) {
?>
<label class="standard_label"><?=$this->element->getLabel()?><?php if($this->element->isRequired()) print "*"; ?></label>
<?php
        } else {
?>            
<span class="<?= $this->labelclass ?>"><?=$this->element->getLabel()?></span><br />            
<?php
        }    
    }
?>
<input id="<?=$this->element->getName()?>" name="<?=$this->element->getName()?>" type="text" placeholder="<?php echo $this->element->getDescription() ?>" <?php if ($this->readonly) print "readonly"; ?> <?php if (!is_null($this->maxlength)) { print "maxlength=\"".$this->maxlength."\""; } ?> value="<?=$this->escape($this->element->getValue())?>" class="standard_input" />