<div class="standard_element_container">    
    <?php
        // label
        if (!is_null($this->element->getLabel())) { //         $this->formLabel($this->element->getName(),$this->element->getLabel())
    ?>
    <label class="standard_label"><?=$this->element->getLabel()?><?php if($this->element->isRequired()) print "*"; ?></label>
    <?php
        }
    ?>
    <select name="<?=$this->element->getName()?>" id="<?=$this->element->getName()?>" <?php if ($this->readonly) print "readonly"; ?> class="standard_select">
    <?php
        foreach ($this->element->getmultiOptions() as $key=>$name) {
    ?>
        <option <?php if($this->element->getValue()==$key) echo 'selected="selected"';  ?> value="<?=$key?>"><?=$name?></option>
    <?php
        }
    ?>
    </select>
    <div class="standard_element_help"><?php echo $this->element->getDescription() ?></div>
</div>



<?php
    if (count($this->element->getMessages()) > 0) {
        //print $this->formErrors($this->element->getMessages())
        foreach ($this->element->getMessages() as $key=>$name) {
?>
<div class="check_error"><span class="COLLECTION"></span><?=$name;?></div>
<?php
        }
    }
?>