<div class="container">

    <div class="Q74">
	
	<?php 
            print $this->PopularPeoples();        
        ?>

        <div class="BRC"><a class="grey" href="<?= $this->url(array(), 'peoples') ?>">Usuarios</a>&nbsp;&nbsp;/&nbsp;&nbsp;<a class="grey" href="<?= $this->url(array('userId' => $this->user->id), 'profile') ?>"><?= $this->user->username ?></a>&nbsp;&nbsp;/&nbsp;&nbsp;<span class="f24 grey">Música</span></div>

        <div class="US1">

            <div class="Qblock Qblock5">
                <?php if (!$this->items): ?>
                    <p class="f18 lh24"><a href="<?= $this->url(array(), 'createmusic') ?>">Cargue su primer lanzamiento de música!</a></p>
                <?php else: ?>

                    <?php
                    $identity = $this->getUserByIdentity();

                    foreach ($this->items as $music) :
                        $photo = $music->getPhoto();
                        $style = $music->getStyle();
                        $user = $music->getUser();
                        $commentCount = (int) $music->commentCount();
                        $musicCounter = $music->getMusicCounter(0);
                        if (!is_null($musicCounter)) {
                            $musicCounter = $musicCounter->counter;    
                        } else {
                            $musicCounter = 0;
                        }
                        ?>

                        <div class="US6">
                            <div class="Qavatar1">
                                <a href="<?= $this->url(array('musicId' => $music->id), 'music') ?>"><img src="/files/music/thumbs/119_<?= $photo ?>" width="119" height="119" alt="" /></a>
                            </div>
                        </div>

                        <div class="QmusicD US8 pull-right">
                            <span><a class="f14" href="<?= $this->url(array('musicId' => $music->id), 'music') ?>"><strong><?= $music->getName() ?></strong></a>&nbsp; <span class="f9 grey"><?= $music->getDate() ?></span><a class="Qtag lnone" href="<?= $this->url(array('categoryId' => $style->id), 'musicstyle') ?>"><?= $style ?></a></span>
                            <br>
                            <span class="grey f11 lh17">2 de junio, 2013 <strong><a class="purple lhov" href=""></a><?= $user->getUserName() ?></strong> publicado</span>
                            <audio id="player2" src="/files/music/<?= $music->getMusicFile() ?>" type="audio/mp3" controls="controls" preload="none"></audio>
                            <div class="w100 clear f10 grey">
                                <a class="grey lnone" href="<?= $this->url(array('musicId' => $music->id), 'music') ?>#commentsList" title="<?= $commentCount ?> commentarios"><img class="Icomm" src="/zeta/0.png" width="10" height="16" alt=""><?= $commentCount ?></a>
                                <a class="grey lnone" href="<?= $this->url(array('musicId' => $music->id), 'music') ?>" title="<?= $music->viewed ?> visites"><img class="Iviews" src="/zeta/0.png" width="10" height="16" alt=""><?= $music->viewed ?></a>
                            <?php
                                if (!$music->isAlbum()) :
                                    if ($music->is_download == 1) :
                            ?>    
                                <a class="grey lnone" href="<?= $this->url(array('musicId' => $music->id, 'songId' => 0), 'downloadmusic') ?>" title="<?= $musicCounter ?> descargas"><img class="Idown" src="/zeta/0.png" width="10" height="16" alt=""><?= $musicCounter ?></a>
                            <?php
                                    endIf;
                                else :
                                    $s_count = count($music->getMusics());
                            ?>
                            <a class="grey lnone" href="<?= $this->url(array('musicId' => $music->id), 'music') ?>" title="<?= $s_count ?> tracks"><img class="Imusix" src="/zeta/0.png" width="10" height="16" alt=""><?= $s_count ?></a>    
                            <?php    
                                endif;
                            ?>
                            </div>
                        </div>

                        <script>
                            $('audio').mediaelementplayer();
                        </script>

                        <div class="w100 clear mb30"></div>                        


                        <?php
                    endforeach;
                    ?>                    

                <?php endif ?>                            
            </div>

        </div>

        <div class="US2 pull-right">

            <?= $this->ProfileMenuControl() ?>

            <?= $this->LugaresNoticias() ?>

        </div>

    </div>

    <?php include('right_block.phtml') ?>

</div>