<?php

    $user_agent = $_SERVER['HTTP_USER_AGENT'];
    if (stripos($user_agent, 'MSIE 6.0') !== false && stripos($user_agent, 'MSIE 8.0') === false && stripos($user_agent, 'MSIE 7.0') === false) {
        if (!isset($HTTP_COOKIE_VARS["ie"])) {
            setcookie("ie", "yes", time()+60*60*24*360);
            header ("Location: /ie6/ie6.html");
        }
    }
    
    echo $this->doctype();
    
?>
<html>
<head>
    
    <meta property="fb:app_id" content="155458191304330"/>
    <meta property="og:site_name" content="Qlick.cl" />
    <?=$this->headMeta()?>    
    <meta property="og:type" content="website" />
    
    <?php 
        echo $this->headTitle();
        echo $this->jQuery(); 
        echo $this->magicHeadLink();
    ?>
    <base href="/" />
    <!--[if IE 7]> <link rel="stylesheet" href="/css/ie.css" type="text/css" media="screen, projection"> <![endif]-->
    <!--[if IE 8]> <link rel="stylesheet" href="/css/ie.css" type="text/css" media="screen, projection"> <![endif]-->
    <link rel="apple-touch-icon" href="/zeta/icontouch.png" />    
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
        
</head>

<body lang="es" onload="initialize()">
    
    <noscript>
        <div>
        <p>Lo sentimos, pero su navegador no tiene JavaScript y es necesario para todas las funciones de nuestra sítio. Eso podria ser por los casos siguientes:</p>
	<ul class="mar-bot3 lh-130">
	<li>Esta usando el navegador muy viejo. Le recomendamos instaliar la última versión de navegador <a class="nl" href="http://www.google.com/chrome">Сhrome</a>.</li>
	<li>Su JavaScript esta desactivado. Como se puede activar <a class="nl" href="http://www.google.com/support/bin/answer.py?answer=23852">conocer aquí</a>.</li></ul>
    </noscript>
    <style>.Qmenu {margin-bottom: 15px;}</style>

    <?php include('toppanel.phtml'); ?>

    <?php
        print $this->flashMessages();
    ?>
    <style>.FOO0 {margin-top: 0;} .Qmenu {margin-bottom: 0;}</style>
    
    <?php
        //if ($this->isGodOfProject()) :
    ?>        
    <div style="display: block; position: absolute; z-index: 99; top: 120px; left: 10%; width: 80%; height: 500px; overflow: scroll; background: rgba(0,0,0,0.9); color: #01cda4; padding: 20px;">
    <?= $this->layout()->content ?>
    </div>
    <?php
        //endIf;
    ?>
    
    <div style="width: 100%; background: #0c0c0c url('/zeta/404.jpg') no-repeat center bottom;">
      <img style="display: block; margin: 140px auto 440px auto;" src="/zeta/4041.png" width="335" height="71" alt="" />
    </div>
    <?php include('footer.phtml'); ?>  
    
    <?php 
        echo $this->magicHeadScript();        
    ?>
    
</body>
</html>
<!-- © 2014 REVISTA INTERNET QLICK.CL (ISKAKOV & BERDNIK CREACIONES LLC.) -->