<div class="Q1 Q1-COM">
	
	<?= $this->profileHead() ?>

<div class="Q1">

	<div class="w74-1">
		
                <div class="BREAK mar-bot"></div>
		
		<?php
		
			if (count($this->list) == 0) :
		?>
		<p class="f150 bold"><em>У этой компании пока нет ни одной вакансии.</em></p>
		<?php	
			endIf;
		
                        $owner = $this->company->getOwner();
                        $identity = $this->getUserByIdentity();
                        if (!is_null($owner) || $this->isGodOfProject()) :                            
                            if ((!is_null($identity) && $owner->id == $identity->id) || $this->isGodOfProject())  :                        
                ?>
                
			<a href="<?=$this->url(array('companyId' => $this->company->id, 'action' => 'new'), 'companyvacancies');?>">Добавить вакансию</a>
		
                <?php 
                            endif;
                        endif;
                ?>
		
		<div class="BREAK mar-bot"></div>
		
		<ul class="VACAN-L BREAK mar-bot3">
                    <?php foreach ($this->list as $vacancy): ?>
                        <li><a class="blue lineon" href="<?=$this->url(array('companyId' => $this->company->id, 'industryId' => $vacancy->industry), 'companyvacanciesindustry');?>"><?= $vacancy->getIndustry() ?></a> <?= $vacancy->positionCount ?></li>
                    <?php endforeach; ?>
                </ul>
                
		<div class="BREAK"></div>
                    <?php if (!empty($this->list_visible)): ?>

                        <?php
				$i = 1;
				foreach ($this->list_visible as $vacancy):
			?>
                            <div class="VACAN-1">				
				
				<h3 class="mar-bot2"><em><?= $vacancy->getIndustry() ?> /</em></h3>
				<a class="black-blue nl" href="<?=$this->url(array('companyId' => $this->company->id, 'vacancyId' => $vacancy->id, 'action' => 'view'), 'companyvacancy')?>">
                                <h2 class="mar-bot lh-100"><?= $vacancy ?></h2>
                                <p class="mar-bot2">Обязанности: <li><?= $vacancy->description ?></li></p>
                                 
                                <?php if ($vacancy->salary_from or $vacancy->salary_to): ?>
                                <p class="f120 bold mar-bot2">з/п
                                <?php if ($vacancy->salary_from != $vacancy->salary_to): ?>
                                    <span class="vacant_wealth">desde <?= $vacancy->getSalaryFrom() ?><?php if ($vacancy->getSalaryTo()): ?> hasta <?= $vacancy->getSalaryTo() ?> руб.<?php endif; ?></span>
                                <?php else: ?>
                                    <span class="vacant_wealth"><?= $vacancy->getSalaryFrom() ?> руб.</span>
                                <?php endif; ?>
                                </p>
                                <?php endif; ?>
				
				
				</a>
				
				<p class="f90"><em>Publicada <?= $this->dateFormatComments($vacancy->date); ?></em></p>				
				
				<div class="VACAN-A">
				<?php
                                if (!is_null($owner) || $this->isGodOfProject()) :                            
                                    if ((!is_null($identity) && $owner->id == $identity->id) || $this->isGodOfProject())  :                        
                                ?><em>
                                <a class="grey" href="<?=$this->url(array('companyId' => $this->company->id, 'vacancyId' => $vacancy->id, 'action' => 'edit'), 'companyvacancy')?>">Редактировать</a> | 
                                <a class="grey" href="<?=$this->url(array('companyId' => $this->company->id, 'vacancyId' => $vacancy->id, 'action' => 'toggle'), 'companyvacancy')?>" id="vacancy-toggle"><?= ($vacancy->visible ? 'Скрыть' : 'Показать') ?></a> |
                                <?php
                                    if ($this->isGodOfProject()) :
                                ?>
                                <a class="grey" href="<?=$this->url(array('companyId' => $this->company->id, 'vacancyId' => $vacancy->id, 'action' => 'hot'), 'companyvacancy')?>" id="vacancy-hot"><?= ($vacancy->is_hot ? 'Убрать с индекса' : 'На индекс') ?></a> |
                                <?php
                                    endIf;
                                ?>
                                <a id="removeVacancy" class="grey" href="<?=$this->url(array('companyId' => $this->company->id, 'vacancyId' => $vacancy->id, 'action' => 'delete'), 'companyvacancy')?>" class="vacancy-delete">Удалить</a></em>

                                <?php 
                                        endif;
                                    endif;
                                ?>                                 
                                </div>
                        
                            </div>                        
                        <?php
				if ($i == 2) :
			?>
				<div class="BREAK mar-bot"></div>				
			<?php
					$i = 0;
				endIf;
				
				$i++;
				endforeach;
			?>

                        <div class="active_unactive_spacer">&nbsp;</div>

                    <?php endif; ?>

                    <?php if (!empty($this->list_hidden)): ?>

                        <p class="f150 bold"><em>Скрытые вакансии</p>

                        <?php
				$i = 1;
				foreach ($this->list_hidden as $vacancy):
			?>
                            <div class="VACAN-1">				
				
				<h3 class="mar-bot2"><em><?= $vacancy->getIndustry() ?> /</em></h3>
				<a class="black-blue nl" href="<?=$this->url(array('companyId' => $this->company->id, 'vacancyId' => $vacancy->id, 'action' => 'view'), 'companyvacancy')?>">
                                <h2 class="mar-bot lh-100"><?= $vacancy ?></h2>
                                <p class="mar-bot2">Обязанности: <li><?= $vacancy->description ?></li></p>
                                 
                                <?php if ($vacancy->salary_from or $vacancy->salary_to): ?>
                                <p class="f120 bold mar-bot2">з/п
                                <?php if ($vacancy->salary_from != $vacancy->salary_to): ?>
                                    <span class="vacant_wealth">desde <?= $vacancy->getSalaryFrom() ?><?php if ($vacancy->getSalaryTo()): ?> hasta <?= $vacancy->getSalaryTo() ?> руб.<?php endif; ?></span>
                                <?php else: ?>
                                    <span class="vacant_wealth"><?= $vacancy->getSalaryFrom() ?> руб.</span>
                                <?php endif; ?>
                                </p>
                                <?php endif; ?>
				
				
				</a>
				
				<p class="f90"><em>Publicada <?= $this->dateFormatComments($vacancy->date); ?></em></p>				
				
				<div class="VACAN-A">
				<?php
                                if (!is_null($owner) || $this->isGodOfProject()) :                            
                                    if ((!is_null($identity) && $owner->id == $identity->id) || $this->isGodOfProject())  :                        
                                ?><em>
                                <a class="grey" href="<?=$this->url(array('companyId' => $this->company->id, 'vacancyId' => $vacancy->id, 'action' => 'edit'), 'companyvacancy')?>">Редактировать</a> | 
                                <a class="grey" href="<?=$this->url(array('companyId' => $this->company->id, 'vacancyId' => $vacancy->id, 'action' => 'toggle'), 'companyvacancy')?>" id="vacancy-toggle"><?= ($vacancy->visible ? 'Скрыть' : 'Показать') ?></a> |
                                <?php
                                    if ($this->isGodOfProject()) :
                                ?>
                                <a class="grey" href="<?=$this->url(array('companyId' => $this->company->id, 'vacancyId' => $vacancy->id, 'action' => 'hot'), 'companyvacancy')?>" id="vacancy-hot"><?= ($vacancy->is_hot ? 'Убрать с индекса' : 'На индекс') ?></a> |
                                <?php
                                    endIf;
                                ?>
                                <a id="removeVacancy" class="grey" href="<?=$this->url(array('companyId' => $this->company->id, 'vacancyId' => $vacancy->id, 'action' => 'delete'), 'companyvacancy')?>" class="vacancy-delete">Удалить</a></em>

                                <?php 
                                        endif;
                                    endif;
                                ?>                                 
                                </div>
                        
                            </div>
                        <?php
				if ($i == 2) :
			?>
				<div class="BREAK mar-bot"></div>				
			<?php
					$i = 0;
				endIf;
				
				$i++;
			
				endforeach;
			?>

                <?php endif; ?>

	</div>
	
	<div class="w25">
		
                <div class="COBAYASHI-RUBIT-BABKI mar-bot">
                    <?= $this->left_banner ?>
                </div>
		
                <div id="fb-root"></div>
                <script>(function(d, s, id) {
                  var js, fjs = d.getElementsByTagName(s)[0];
                  if (d.getElementById(id)) return;
                  js = d.createElement(s); js.id = id;
                  js.src = "//connect.facebook.net/ru_RU/all.js#xfbml=1";
                  fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));</script>
                <fb:like-box href="http://www.facebook.com/pages/Qlick/265987913519758?ref=hl" width="292" show_faces="true" stream="false" header="false"></fb:like-box>
		
	</div>
</div>


<?php
    if (!is_null($owner) || $this->isGodOfProject()) :                            
        if ((!is_null($identity) && $owner->id == $identity->id) || $this->isGodOfProject())  :
?>
<script type="text/javascript">
$(function(){
    $('#removeVacancy').live('click',function() {
        if ( !confirm('Вы действительно хотите удалить данную вакансию?') ) {
            return false;
        }
    });
<?php
            if ($this->isGodOfProject()) :
?>
    $('#vacancy-hot').live('click',function() {
        var el = $(this);
        $.ajax({
            url: el.attr('href'),
            type: 'post',
            success: function( data ) {
                el.html(data);
            }
        });
        return false;
    }); 
    
<?php
            endIf;
?>    
}); 
</script>
<?php
        endIf;
    endif;
?>