<div class="container">

	<div class="w100 mb10"></div>
	
	<div class="Q74">
		
		<?php 
                    //include('popular_companies.phtml') 
                    print $this->PopularPosts();
                ?>
        
		<div class="BRC">
			<a class="grey" href="<?= $this->url(array(), 'companies') ?>">Lugares y empresas</a>&nbsp;&nbsp;/&nbsp;&nbsp;<a class="grey" href="<?= $this->url(array('company_type' => $this->company->getTypeUrl()), 'companybytype') ?>"><?= Companies_Model_Company::$header_types[$this->company->type] ?></a>&nbsp;&nbsp;/&nbsp;&nbsp;<span class="f24 grey"><?= $this->company->name ?></span>
		<?php
                        $identity = Zend_Auth::getInstance()->getIdentity();
                        $owner = $this->company->getOwner();
                        if (!is_null($identity) || $this->isGodOfProject()) :
                            if (($owner && $owner->id == $identity->id) || $this->isGodOfProject())  :
                    ?>
                        &nbsp;&nbsp;
                        <a href="<?= $this->url(array('companyId' => $this->company->id, 'action' => 'edit'), 'company') ?>" title="Editar"><img class="Ieditar" src="/zeta/0.png" width="29" height="29" alt="" /></a>
                        <a id="event-delete" href="<?= $this->url(array('companyId' => $this->company->id, 'action' => 'delete'), 'company') ?>" title="Eliminar"><img class="Ieliminar" src="/zeta/0.png" width="29" height="29" alt="" /></a>
                    <?php
                            endIf;
                        endIf;
                    ?>
		</div>
	    
		<div class="Q31">
                    <?= $this->profileHead() ?>
		    
		    <?= $this->LugaresNoticias() ?>		    
		</div>
		<div class="Q64">
                    
                    <div class="Qblock Qblock5">
                    <?php
                        if (count($this->items) > 0) :
                            
                            foreach ($this->items as $post) :
                            
                                $photo = $post->getPhoto();
                                $category = $post->getRubric();
                                $commentCount = (int) $post->commentCount();
                                $post_url = $post->getUrl();
                            ?>
                            <div class="US10">

                                <div class="US6">
                                    <div class="Qavatar1">
                                        <a href="<?= $post_url ?>"><img src="/files/post/thumbs/119_<?= $photo ?>" width="119" height="119" alt="" /></a>
                                    </div>
                                </div>

                                <div class="US8">
                                    <p class="f18"><a class="lhov" href="<?= $post_url ?>"><?= $post->name ?></a></p>
                                    <p class="f11 grey2 lh17">
                                        <?= $post->description ?>
                                    </p>
                                    <p class="f11 lh17">
                                    <div>Categoría: <a class="purple" href="<?= $this->url(array('theme_url' => mb_strtolower($category, 'UTF-8')), 'theme_seo') ?>"><?= $category->name ?></a></div>

                                    <div class="US9 f10 grey">
                                        <a class="grey lnone" href="<?= $post_url ?>#commentsList" title="<?= $commentCount ?> commentarios"><img class="Icomm" src="/zeta/0.png" width="10" height="16" alt=""><?= $commentCount ?></a>
                                        <a class="grey lnone" href="<?= $post_url ?>" title="<?= $post->viewed ?> visites"><img class="Iviews" src="/zeta/0.png" width="10" height="16" alt=""><?= $post->viewed ?></a>
                                    </div>
                                    </p>
                                </div>

                            </div>       
                    <?php
                            endForeach;

                        else :
                    ?>
                    No hay blogs
                    <?php        
                        endIf;
                    ?>
                    </div>
                    
		</div>
		
	</div>
	
        <?php include('right_block.phtml') ?>

</div>