<?php
    $locationOnMap = $this->company->getLocationOnMap();
?>
<script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false&language=es"></script> 
<script type="text/javascript">
    var myLatlng = new google.maps.LatLng('<?php print $locationOnMap->lat; ?>', '<?php print $locationOnMap->lng; ?>');
    var marker      = null;
    
    function initialize() {
        var myOptions = {
          zoom: 19,
          center: myLatlng,
          mapTypeId: google.maps.MapTypeId.SATELLITE,
          name: "Santiago"
        };
        map = new google.maps.Map(document.getElementById("map_canvas"),myOptions);

        
        new google.maps.Marker({
          position: myLatlng,
          map: map,
          clickable: false,
          id: "marker",
          icon: "/sprites/map/large/<?=$locationOnMap->icon?>"
        });        

    }
    
    $(function(){
        initialize();
    })
</script>


<div class="Q1 Q1-COM">
	<?=$this->profileHead()?>
        
<div class="Q1">
    
    <div class="w74-1">
        
        <div class="BREAK mar-bot3"></div>
        <div id="map_canvas" style="border: 1px #AAA solid; width:100%; height:500px;"></div>
        
    </div>
    
    <div class="w25">
        
        <div class="COBAYASHI-RUBIT-BABKI mar-bot">
            <?= $this->left_banner ?>
        </div>
        
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/ru_RU/all.js#xfbml=1";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
        <fb:like-box href="http://www.facebook.com/pages/Qlick/265987913519758?ref=hl" width="292" show_faces="true" stream="false" header="false"></fb:like-box>
        
    </div>
    
</div>