<div id="m1">
    <div id="m2" class="m-form">
<style>
            .Q0 {background: transparent !important;
            box-shadow: none !important;
            -webkit-box-shadow: none !important;
            -moz-box-shadow: none !important;
            }
            .horde, .Q-TOP {display: none;}
            .MM-1 {margin-top: 30px;}
            .PRF-11 {padding-top: 0 !important;}
            #results_branches_bar {width: 830px; padding: 20px 0 0 40px;}
            #results_branches_bar li {float: left; margin-right: 20px;font-size: 160%; font-weight: bold;}
        </style>
        <?=$this->addform?>
    </div>
</div>