
<div class="Q1">
    
    <div class="w74-1">
        
        <h3 class="KOMP-3">Автокомпании</h3>
        <ul class="KOMP-1 BREAK">
            
        <?php
            foreach ($this->spheres as $root) :
                foreach ($root['subs'] as $id=>$sub) :                            
            ?>
                <li class="w33 mar-bot f120"><strong><a class="blue lineon" href="<?= $this->url(array('sphereId' => $id), 'companybysphere') ?>"><?= $sub ?></a></strong> <span><?= $sub->companies_count ?></span></li>    
            <?php                            
                endForeach;
                
            endForeach;
        ?>
        </ul>
        <?php
            if (count($this->companies) > 0) :
        ?>
        <div id="company_list" class="BREAK">
            <?php 
                $k = 0;
                foreach($this->companies as $company) : 
                    $k++;
                    if ($k == 4) { print '<div class="unt">'; } else print '<div class="unt">';
                    include('company_list.phtml');
            ?>
            </div>    
            <?php
                    if ($k == 5) { print '<div class="BREAK mar-bot3"></div>'; $k = 0; }
                endForeach;
            ?>
        </div>
        <?php
            endIf
        ?>        
        
    </div>
    
    <div class="w25">
        
        <div class="COBAYASHI-RUBIT-BABKI mar-bot">
            <?= $this->left_banner ?>
        </div>
        
        <div id="vk_groups"></div>
        <script type="text/javascript">
        VK.Widgets.Group("vk_groups", {mode: 0, width: "256", height: "300"}, 26971787);
        </script>
        
    </div>

</div>