<div id="m1">
    <div id="m2" class="m-form">
<style>
            .Q0 {background: transparent !important;
            box-shadow: none !important;
            -webkit-box-shadow: none !important;
            -moz-box-shadow: none !important;
            }
            .horde, .Q-TOP {display: none;}
            .MM-1 {margin-top: 30px;}
            .PRF-11 {padding-top: 0 !important;}
            #results_branches_bar {width: 830px; padding: 20px 0 0 40px;}
            #results_branches_bar li {float: left; margin-right: 20px;font-size: 160%; font-weight: bold;}
        </style>
        <div id="fr-h">
            <div>
            <a href="/auto"><img class="COLLECTION i-back" width="28" height="29" src="/sprites/null.png" alt="" /></a>
            <a class="straight lineon" href="/auto">Все объявления</a>
            <h2>Продаем автомобиль</h2>
            <span>Поля со знаком * обязательны для заполнения<br />
            Если возникли сложности &mdash; <a class="blue" href="mailto:support@qlick.ru">напишите</a> нам или позвоните. Мы обязательно поможем.<br />Для компаний, занимающихся продажей автомобилей, у нас есть интересное предложение.
            </span>
            </div>
        </div>
        <?=$this->addform?>
    </div>
</div>